services:
  - type: web
    name: ucak-siniflandirici
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
